# Generated by Django 3.1.4 on 2021-02-07 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='leaders', to=settings.AUTH_USER_MODEL),
        ),
    ]
