LOREM = ['Lorem', 'ipsum', 'dolor', 'sit', 'amet,', 'consectetur',
         'adipiscing', 'elit,', 'sed', 'do', 'eiusmod', 'tempor', 'incididunt',
         'ut', 'labore', 'et', 'dolore', 'magna', 'aliqua.', 'Convallis',
         'tellus', 'id', 'interdum', 'velit', 'laoreet', 'id', 'donec',
         'ultrices', 'tincidunt.', 'Facilisis', 'mauris', 'sit', 'amet',
         'massa', 'vitae', 'tortor', 'condimentum.', 'Gravida', 'quis',
         'blandit', 'turpis', 'cursus', 'in', 'hac', 'habitasse', 'platea',
         'dictumst.', 'Adipiscing', 'elit', 'ut', 'aliquam', 'purus', 'sit',
         'amet', 'luctus', 'venenatis', 'lectus.', 'Aliquet', 'enim', 'tortor',
         'at', 'auctor', 'urna', 'nunc', 'id.', 'Justo', 'laoreet', 'sit',
         'amet', 'cursus', 'sit', 'amet', 'dictum.', 'Pulvinar', 'etiam',
         'non', 'quam', 'lacus', 'suspendisse', 'faucibus', 'interdum',
         'posuere', 'lorem.', 'Dui', 'accumsan', 'sit', 'amet', 'nulla',
         'facilisi', 'morbi.', 'A', 'diam', 'maecenas', 'sed', 'enim.',
         'Ultricies', 'mi', 'eget', 'mauris', 'pharetra', 'et', 'ultrices',
         'neque', 'ornare', 'aenean.', 'Imperdiet', 'dui', 'accumsan', 'sit',
         'amet', 'nulla', 'facilisi', 'morbi', 'tempus', 'iaculis.', 'At',
         'imperdiet', 'dui', 'accumsan', 'sit', 'amet.', 'Aliquam', 'eleifend',
         'mi', 'in', 'nulla', 'posuere', 'sollicitudin', 'aliquam',
         'ultrices.', 'Pellentesque', 'id', 'nibh', 'tortor', 'id', 'aliquet',
         'lectus', 'proin', 'nibh.', 'Neque', 'vitae', 'tempus', 'quam',
         'pellentesque', 'nec', 'nam', 'aliquam', 'sem.', 'Ipsum', 'dolor',
         'sit', 'amet', 'consectetur.', 'Sapien', 'pellentesque', 'habitant',
         'morbi', 'tristique', 'senectus', 'et.', 'Consequat', 'mauris',
         'nunc', 'congue', 'nisi', 'vitae', 'suscipit', 'tellus', 'mauris.',
         'Massa', 'sed', 'elementum', 'tempus', 'egestas', 'sed', 'sed',
         'risus', 'pretium', 'quam.']
